use slug::slugify;
use std::env;
use std::io;

fn main() {
    let mut line = String::new();

    // Parse cli arguments
    let args: Vec<String> = env::args().collect();
    if args.len() != 2 {
        println!("Wrong number of arguments!")
    } else {
        println!("Enter a string:");
        // Read a string from stdin
        io::stdin()
            .read_line(&mut line)
            .expect("Failed to read line");
        let line = line.trim();
        println!("Original: {line}");

        let transformed = transform_string(&line, &args[1]);
        match transformed {
            Some(result) => println!("Transformed result: {}", result),
            None => println!("Unknown argument!"),
        }
    }
}

fn transform_string(line: &str, transformation: &str) -> Option<String> {
    match transformation {
        // Compulsory transformations
        "lowercase" => Some(line.to_lowercase()),
        "uppercase" => Some(line.to_uppercase()),
        "no-spaces" => Some(line.replace(" ", "")),
        "slugify" => Some(slugify(&line)),
        // Bonus transofrmations
        "double" => Some(format!("{}{}", line, line)),
        "reverse" => Some(line.chars().rev().collect()),
        _ => None, // Default case for any other value
    }
}

// Add unit tests generated by ChatGPT
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lowercase() {
        assert_eq!(
            transform_string("Hello, World!", "lowercase"),
            Some("hello, world!".to_string())
        );
    }

    #[test]
    fn test_uppercase() {
        assert_eq!(
            transform_string("Hello, World!", "uppercase"),
            Some("HELLO, WORLD!".to_string())
        );
    }

    #[test]
    fn test_no_spaces() {
        assert_eq!(
            transform_string("Hello, World!", "no-spaces"),
            Some("Hello,World!".to_string())
        );
    }

    #[test]
    fn test_slugify() {
        assert_eq!(
            transform_string("Hello, World!", "slugify"),
            Some("hello-world".to_string())
        );
    }

    #[test]
    fn test_double() {
        assert_eq!(
            transform_string("Hello, World!", "double"),
            Some("Hello, World!Hello, World!".to_string())
        );
    }

    #[test]
    fn test_reverse() {
        assert_eq!(
            transform_string("Hello, World!", "reverse"),
            Some("!dlroW ,olleH".to_string())
        );
    }

    #[test]
    fn test_unknown_argument() {
        assert_eq!(transform_string("Hello, World!", "unknown"), None);
    }
}
